"""DRP score-fan-out flood control — brand:fingerprint_identity tool tests.

F2 (verified root cause): the asset-only bootstrap/cadence path dispatches
this tool with `referenceUrls: []` + a synthesized SCREENSHOT reference asset.
The progress reporter indexed `reference_urls[0]` → IndexError → the
fingerprint stayed GENERATING forever, the broken legacy v1 remained the
eternal "latest READY", and the 24h cadence re-minted a new stuck version
daily (44 stuck rows, versions to 18).

Covers:
  - asset-only path no longer raises IndexError (both progress sites)
  - the asset-only path does NOT launch a browser at all (playwright skipped
    when there are no reference URLs)
  - empty input (no URLs, no assets) still returns the structured fail
"""

import asyncio
import io
import sys

import pytest

from tools.brand_fingerprint_identity import BrandFingerprintIdentityTool, _phash_image_bytes


def _multi_content_ico(images):
    """Assemble a real .ico container with DISTINCT content per frame (PNG-encoded
    entries). Unlike PIL's single-source ICO save, this lets each frame differ so
    frame-SELECTION is observable in the phash."""
    import struct
    pngs = []
    for im in images:
        b = io.BytesIO()
        im.save(b, format='PNG')
        pngs.append(b.getvalue())
    n = len(pngs)
    out = struct.pack('<HHH', 0, 1, n)  # ICONDIR
    offset = 6 + 16 * n
    entries = b''
    for im, png in zip(images, pngs):
        w, h = im.size
        entries += struct.pack('<BBBBHHII', w % 256, h % 256, 0, 0, 1, 32, len(png), offset)
        offset += len(png)
    return out + entries + b''.join(pngs)


def _img(size, fill, paste=None):
    from PIL import Image
    im = Image.new('RGBA', (size, size), fill)
    if paste:
        im.paste(paste, (0, 0, size // 2, size))  # half-and-half pattern
    return im


class TestFaviconIcoDeterminism:
    """FAV-4 — a multi-resolution .ico must hash by the LARGEST frame
    deterministically (PIL's default frame choice is version-dependent)."""

    def test_largest_frame_selected_not_a_smaller_one(self):
        small_black = _img(16, (0, 0, 0, 255))
        large_pattern = _img(64, (255, 255, 255, 255), paste=(0, 0, 0, 255))
        multi = _multi_content_ico([small_black, large_pattern])
        # Selecting the largest (64x64 pattern) frame → matches a 64-only icon …
        assert _phash_image_bytes(multi) == _phash_image_bytes(
            _multi_content_ico([large_pattern])
        )
        # … and is NOT the small black frame's hash (the no-op would pick it).
        assert _phash_image_bytes(multi) != _phash_image_bytes(
            _multi_content_ico([small_black])
        )

    def test_byte_identical_ico_equal_hash(self):
        b = _multi_content_ico([_img(16, (10, 20, 30, 255)), _img(64, (200, 30, 30, 255))])
        assert _phash_image_bytes(b) == _phash_image_bytes(b)

    def test_non_image_bytes_returns_none(self):
        assert _phash_image_bytes(b'not-an-image') is None


class FakeAgent:
    """Captures progress calls so we can assert the [0]-site behavior."""

    def __init__(self):
        self.progress_calls = []
        self.outputs = []

    def report_progress(self, **kwargs):
        self.progress_calls.append(kwargs)

    def append_output(self, line):
        self.outputs.append(line)


def run_tool(params):
    tool = BrandFingerprintIdentityTool()
    return asyncio.run(tool.execute(params))


class TestAssetOnlyPath:
    def test_asset_only_no_longer_raises_index_error(self, monkeypatch):
        # Poison playwright: the asset-only path must not import/launch it.
        monkeypatch.setitem(sys.modules, 'playwright', None)
        monkeypatch.setitem(sys.modules, 'playwright.async_api', None)

        agent = FakeAgent()
        result = run_tool({
            'referenceUrls': [],
            'referenceAssets': [
                {
                    'id': 'auto-original-screenshot-mon-1',
                    'type': 'SCREENSHOT',
                    'fileName': 'Original Homepage Baseline.png',
                    # Nonexistent file → hash gracefully degrades to None;
                    # the point of THIS test is the IndexError + browser skip.
                    'filePath': '/nonexistent/original.png',
                    'isAutoGenerated': True,
                },
            ],
            'brandMonitorId': 'mon-1',
            '_agent': agent,
        })

        # Pre-fix this raised IndexError at the first report_progress.
        assert result['success'] is True
        assert result['output']['brandMonitorId'] == 'mon-1'
        assert result['output']['referenceUrlsProcessed'] == 0

        # Both progress sites used the guarded placeholder target.
        targets = [c.get('current_target') for c in agent.progress_calls]
        assert targets, 'progress should still be reported on the asset-only path'
        assert all(t == 'reference-assets' for t in targets)

    def test_asset_only_emits_fingerprint_vector_with_assets(self, monkeypatch):
        monkeypatch.setitem(sys.modules, 'playwright', None)
        monkeypatch.setitem(sys.modules, 'playwright.async_api', None)

        result = run_tool({
            'referenceUrls': [],
            'referenceAssets': [
                {'type': 'LOGO', 'fileName': 'logo.png', 'filePath': '/nonexistent/logo.png'},
            ],
            'brandMonitorId': 'mon-1',
        })
        assert result['success'] is True
        fp = result['output']['fingerprint']
        # The uploaded asset is carried through the vector even when its
        # bytes were unavailable for hashing.
        assert fp['fingerprintVector']['referenceAssets'][0]['fileName'] == 'logo.png'

    def test_no_urls_and_no_assets_is_a_structured_fail(self):
        result = run_tool({
            'referenceUrls': [],
            'referenceAssets': [],
            'brandMonitorId': 'mon-1',
        })
        assert result['success'] is False
        assert 'at least one reference URL' in result['error']

    def test_missing_brand_monitor_id_is_a_structured_fail(self):
        result = run_tool({
            'referenceUrls': [],
            'referenceAssets': [{'type': 'LOGO', 'filePath': '/x.png'}],
        })
        assert result['success'] is False
        assert 'brandMonitorId' in result['error']
