#!/usr/bin/env python3
"""
agent/scripts/generate_tool_taxonomy.py  (issue #559)

Generate the tool-taxonomy artifacts from the SINGLE SOURCE OF TRUTH (the plugin
``metadata`` declared on every agent tool):

  - docs/tool-taxonomy.md                              (human-readable catalog)
  - backend/prisma/seeds/tool-taxonomy.generated.json  (seed input; committed)

Agent-tool metadata is read from the LIVE plugins via the running agent container
(the tool modules need the agent's Python deps to import). Platform-only tools
with no ``agent/tools/*.py`` file (e.g. Nessus) are merged from
``agent/tools/_taxonomy_platform_supplement.json``.

Usage (run on the host; needs docker):
    python3 agent/scripts/generate_tool_taxonomy.py          # write artifacts
    python3 agent/scripts/generate_tool_taxonomy.py --check  # fail if stale (CI/pre-commit)

Exit codes: 0 = ok; 2 = could not read plugin metadata; 3 = canonical validation
failed; 4 = artifacts stale (only with --check).
"""
import json
import os
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AGENT_DIR = os.path.dirname(SCRIPT_DIR)
REPO_ROOT = os.path.dirname(AGENT_DIR)
sys.path.insert(0, os.path.join(AGENT_DIR, "tools"))
import _taxonomy  # noqa: E402

DOCS_PATH = os.path.join(REPO_ROOT, "docs", "tool-taxonomy.md")
GENERATED_JSON = os.path.join(
    REPO_ROOT, "backend", "prisma", "seeds", "tool-taxonomy.generated.json"
)
GENERATED_REGISTRY_JSON = os.path.join(
    REPO_ROOT, "backend", "prisma", "seeds", "tool-registry.generated.json"
)
SUPPLEMENT_JSON = os.path.join(AGENT_DIR, "tools", "_taxonomy_platform_supplement.json")
BANNER = "<!-- GENERATED by agent/scripts/generate_tool_taxonomy.py — do not edit by hand. Source of truth: agent tool plugin metadata (#559). -->"

# Snippet executed INSIDE the agent container to dump live plugin metadata.
DUMP_SNIPPET = r"""
import json, sys, io, contextlib
sys.path.insert(0, "/app")
from main_rest import load_config
from plugin_loader import PluginLoader
cfg = load_config()
pl = PluginLoader(cfg)
buf = io.StringIO()
with contextlib.redirect_stdout(buf):
    pl.load_plugins()
out = [{"name": p.name, "description": p.description, "metadata": p.metadata,
        "schema": getattr(p, "schema", {}) or {}}
       for p in pl.plugins.values()]
sys.stdout.write("__TAXJSON__" + json.dumps(out))
"""


def dump_agent_tools():
    """Load live plugin metadata from the running agent container."""
    for base in (["docker", "compose"], ["docker-compose"]):
        cmd = base + ["exec", "-T", "agent", "python3", "-c", DUMP_SNIPPET]
        try:
            res = subprocess.run(
                cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=180
            )
        except FileNotFoundError:
            continue
        marker = res.stdout.find("__TAXJSON__")
        if marker >= 0:
            return json.loads(res.stdout[marker + len("__TAXJSON__"):])
    sys.stderr.write(
        "ERROR: could not read tool metadata from the agent container.\n"
        "Is the stack up? (docker compose up -d agent)\n"
    )
    sys.exit(2)


def load_supplement():
    if not os.path.exists(SUPPLEMENT_JSON):
        return {}
    data = json.load(open(SUPPLEMENT_JSON))
    return {k: v for k, v in data.items() if not k.startswith("_")}


def build(tools, supplement):
    """Return (records_by_name, errors).

    records_by_name[name] = {merged, description, source, category, alias_of}
    """
    records = {}
    for tool in tools:
        name = tool["name"]
        meta = tool.get("metadata") or {}
        records[name] = {
            "merged": _taxonomy.merge_canonical(name, meta),
            "description": (tool.get("description") or "").strip(),
            "source": "agent",
            "category": meta.get("category"),
            "plugin_category": meta.get("category"),
            "schema": tool.get("schema") or {},
            "alias_of": meta.get("alias_of"),
        }
    # Resolve alias_of: aliases inherit the target's canonical taxonomy.
    for rec in records.values():
        alias = rec["alias_of"]
        if alias and alias in records:
            rec["merged"] = dict(records[alias]["merged"])
    # Platform-only supplement tools (no agent file).
    for name, sup in supplement.items():
        domains = sup.get("taxonomyDomains") or [sup.get("taxonomyDomain", "web")]
        records[name] = {
            "merged": {
                "taxonomy_domain": domains,
                "lifecycle_phase": sup.get("lifecyclePhase"),
                "purpose_count": sup.get("purposeCount", "single"),
                "primary_purpose": sup.get("primaryPurpose", ""),
                "secondary_purposes": sup.get("secondaryPurposes", []),
            },
            "description": (sup.get("description") or "").strip(),
            "source": "platform",
            "category": sup.get("category"),
            "alias_of": None,
        }
    errors = []
    for name, rec in records.items():
        errors.extend(_taxonomy.validate(name, rec["merged"]))
    return records, errors


def to_generated_json(records):
    return {
        name: _taxonomy.to_registry_entry(rec["merged"])
        for name, rec in sorted(records.items())
    }


def to_registry_json(records):
    """Full ToolRegistryEntry payloads for AGENT tools (they carry a schema +
    plugin category). Platform-only tools are already registry rows seeded
    elsewhere, so they are skipped here. The seed CREATEs any of these that are
    missing and backfills empty inputSchema — completing the registry from the
    real agent capability set (#559 follow-up)."""
    out = {}
    for name, rec in sorted(records.items()):
        if rec.get("source") != "agent":
            continue
        merged = rec["merged"]
        domains = merged.get("taxonomy_domain") or ["web"]
        category = _taxonomy.registry_category(rec.get("plugin_category"), domains)
        out[name] = {
            "displayName": _taxonomy.display_name_for(name),
            "category": category,
            "domain": domains[0],
            "phase": merged.get("lifecycle_phase"),
            "riskLevel": _taxonomy.registry_risk(category),
            "adapterKind": "NATIVE_AGENT",
            "inputSchema": rec.get("schema") or {},
            **_taxonomy.to_registry_entry(merged),
        }
    return out


def validate_registry(registry):
    """Every synced registry row must use an EXISTING persona-filter category, so
    completing the registry never introduces a new dispatch key."""
    return [
        f"{name}: registry category '{e['category']}' not in REGISTRY_CATEGORIES"
        for name, e in registry.items()
        if e["category"] not in _taxonomy.REGISTRY_CATEGORIES
    ]


def _phase_sort_key(name_rec):
    _, rec = name_rec
    phase = rec["merged"].get("lifecycle_phase")
    return (_taxonomy.PHASE_ORDINAL.get(phase, 99), name_rec[0])


def render_markdown(records):
    total = len(records)
    multi = [n for n, r in records.items() if r["merged"].get("purpose_count") == "multi"]
    by_phase, by_domain = {}, {}
    for rec in records.values():
        by_phase[rec["merged"]["lifecycle_phase"]] = (
            by_phase.get(rec["merged"]["lifecycle_phase"], 0) + 1
        )
        by_domain[rec["merged"]["taxonomy_domain"][0]] = (
            by_domain.get(rec["merged"]["taxonomy_domain"][0], 0) + 1
        )

    lines = [BANNER, "", "# Tool Taxonomy", ""]
    lines += [
        "Canonical purpose/phase/domain map for every agent tool (issue #559).",
        "",
        "- **Single source of truth:** the `metadata` property on each agent tool "
        "plugin (`agent/tools/*.py`), enriched/backfilled by `agent/tools/_taxonomy.py`.",
        "- Platform-only tools (no agent file, e.g. Nessus) are declared in "
        "`agent/tools/_taxonomy_platform_supplement.json`.",
        "- Regenerate with `python3 agent/scripts/generate_tool_taxonomy.py` "
        "(or `npm run taxonomy:generate` in `backend/`). **Do not edit by hand.**",
        "",
        f"**{total} tools** · **{len(multi)} multi-purpose** · "
        f"{len(by_domain)} domains · {len(by_phase)} lifecycle phases.",
        "",
        "## Dimensions",
        "",
        "| Dimension | Canonical values |",
        "|---|---|",
        "| **Domain** | " + ", ".join(f"`{d}`" for d in _taxonomy.DOMAIN_PRIORITY) + " |",
        "| **Lifecycle phase** | "
        + ", ".join(
            f"`{p}`"
            for p in sorted(_taxonomy.CANONICAL_PHASES, key=lambda x: _taxonomy.PHASE_ORDINAL.get(x, 99))
        )
        + " |",
        "| **Purpose count** | `single`, `multi` |",
        "",
        "## Counts by lifecycle phase",
        "",
        "| Phase | Tools |",
        "|---|---|",
    ]
    for phase in sorted(by_phase, key=lambda x: _taxonomy.PHASE_ORDINAL.get(x, 99)):
        lines.append(f"| `{phase}` | {by_phase[phase]} |")
    lines += ["", "## Counts by primary domain", "", "| Domain | Tools |", "|---|---|"]
    for dom in sorted(by_domain, key=lambda d: _taxonomy.DOMAIN_PRIORITY.index(d) if d in _taxonomy.DOMAIN_PRIORITY else 99):
        lines.append(f"| `{dom}` | {by_domain[dom]} |")

    # Multi-purpose tools — modes enumerated (acceptance criterion #2).
    lines += ["", "## Multi-purpose tools — modes", ""]
    if multi:
        lines += ["| Tool | Domain(s) | Mode | Purpose |", "|---|---|---|---|"]
        for name in sorted(multi):
            rec = records[name]
            doms = " / ".join(rec["merged"]["taxonomy_domain"])
            for i, sp in enumerate(rec["merged"].get("secondary_purposes", [])):
                tool_cell = f"`{name}`" if i == 0 else ""
                dom_cell = doms if i == 0 else ""
                lines.append(f"| {tool_cell} | {dom_cell} | `{sp.get('mode')}` | {sp.get('purpose')} |")
    else:
        lines.append("_None._")

    # Full catalog grouped by lifecycle phase.
    lines += ["", "## Full catalog (by lifecycle phase)", ""]
    items = sorted(records.items(), key=_phase_sort_key)
    current_phase = None
    for name, rec in items:
        phase = rec["merged"]["lifecycle_phase"]
        if phase != current_phase:
            current_phase = phase
            lines += [
                "",
                f"### `{phase}`",
                "",
                "| Tool | Domain(s) | Purpose | Primary purpose | Source |",
                "|---|---|---|---|---|",
            ]
        m = rec["merged"]
        doms = " / ".join(f"`{d}`" for d in m["taxonomy_domain"])
        pc = m["purpose_count"]
        pc_cell = f"**{pc}**" if pc == "multi" else pc
        primary = m["primary_purpose"].replace("|", "\\|")
        lines.append(
            f"| `{name}` | {doms} | {pc_cell} | {primary} | {rec['source']} |"
        )
    return "\n".join(lines) + "\n"


def main():
    check = "--check" in sys.argv
    tools = dump_agent_tools()
    supplement = load_supplement()
    records, errors = build(tools, supplement)
    if errors:
        sys.stderr.write("Canonical taxonomy validation FAILED:\n")
        for e in errors:
            sys.stderr.write(f"  - {e}\n")
        sys.exit(3)

    generated = to_generated_json(records)
    json_text = json.dumps(generated, indent=2, sort_keys=True) + "\n"
    md_text = render_markdown(records)

    registry = to_registry_json(records)
    registry_errors = validate_registry(registry)
    if registry_errors:
        sys.stderr.write("Registry mapping validation FAILED:\n")
        for e in registry_errors:
            sys.stderr.write(f"  - {e}\n")
        sys.exit(3)
    registry_text = json.dumps(registry, indent=2, sort_keys=True) + "\n"

    if check:
        stale = []
        for path, fresh in (
            (GENERATED_JSON, json_text),
            (DOCS_PATH, md_text),
            (GENERATED_REGISTRY_JSON, registry_text),
        ):
            existing = open(path).read() if os.path.exists(path) else None
            if existing != fresh:
                stale.append(path)
        if stale:
            sys.stderr.write(
                "Tool-taxonomy artifacts are STALE. Run "
                "`python3 agent/scripts/generate_tool_taxonomy.py`:\n"
            )
            for p in stale:
                sys.stderr.write(f"  - {os.path.relpath(p, REPO_ROOT)}\n")
            sys.exit(4)
        print(f"Tool taxonomy up to date ({len(records)} tools).")
        return

    os.makedirs(os.path.dirname(GENERATED_JSON), exist_ok=True)
    os.makedirs(os.path.dirname(DOCS_PATH), exist_ok=True)
    open(GENERATED_JSON, "w").write(json_text)
    open(DOCS_PATH, "w").write(md_text)
    open(GENERATED_REGISTRY_JSON, "w").write(registry_text)
    print(
        f"Wrote {os.path.relpath(GENERATED_JSON, REPO_ROOT)}, "
        f"{os.path.relpath(DOCS_PATH, REPO_ROOT)} and "
        f"{os.path.relpath(GENERATED_REGISTRY_JSON, REPO_ROOT)} "
        f"({len(records)} tools, {len(registry)} agent registry rows, "
        f"{sum(1 for r in records.values() if r['merged']['purpose_count'] == 'multi')} multi-purpose)."
    )


if __name__ == "__main__":
    main()
