"""
Shared utility functions for screenshot tools (gowitness_screenshot, brand_monitor_screenshot).
"""

import glob as _glob
import hashlib
import os
import shlex
import shutil
import tempfile
from typing import Optional

# #1572 — Chrome features force-disabled for capture runs (see the launcher shim
# below). Chromium's HTTPS-Upgrades / HTTPS-First "balanced" machinery silently
# upgrades every http:// navigation to https:// and, in headless/automation,
# surfaces a failed upgrade as net::ERR_BLOCKED_BY_CLIENT instead of falling
# back to http — so any http-only host whose 443 is TLS-broken or filtered
# becomes uncapturable (raw headless renders a blank page; BOTH gowitness
# drivers, chromedp and gorod, report the blocked navigation). The capture
# pipeline implements its own explicit scheme fallback (https<->http in
# brand_monitor_screenshot._capture_screenshot), so the browser must load
# exactly the scheme it is asked for. Env-tunable so cloud can adjust without a
# code change (same pattern as DRP_GOWITNESS_*); set to an empty string to
# disable the shim entirely (kill-switch — the real binary is used unwrapped).
DEFAULT_CHROME_DISABLE_FEATURES = (
    'HttpsUpgrades,HttpsFirstBalancedMode,HttpsFirstBalancedModeAutoEnable'
)

# POSIX sh (no bash-isms): merges any --disable-features the caller (gowitness's
# chromedp exec allocator) already passes with ours — Chromium keeps only ONE
# value for a repeated switch, so blindly appending would drop chromedp's own
# list — then execs the real Chrome IN PLACE. `exec` preserves the PID, so
# Chrome stays exactly where gowitness put it in the process group and the #571
# group-teardown discipline (register_group/terminate_group) is untouched.
_SHIM_TEMPLATE = """#!/bin/sh
# xasm capture chrome shim (#1572) — generated by screenshot_utils.py; do not edit.
merged={features}
i=0
n=$#
while [ $i -lt $n ]; do
  a=$1; shift
  case "$a" in
    --disable-features=*) merged="${{a#--disable-features=}},$merged" ;;
    *) set -- "$@" "$a" ;;
  esac
  i=$((i+1))
done
exec {real} "$@" --disable-features="$merged"
"""


def _disable_features() -> str:
    return os.environ.get(
        'DRP_CHROME_DISABLE_FEATURES', DEFAULT_CHROME_DISABLE_FEATURES
    ).strip()


def _find_real_chrome() -> Optional[str]:
    """Locate the real Chrome/Chromium binary, or None when absent."""
    real = shutil.which('google-chrome')
    if real:
        return real
    candidates = _glob.glob('/root/.cache/ms-playwright/*/chrome-linux/chrome')
    if candidates:
        return candidates[0]
    return None


def _chrome_shim_path(real_chrome: str, features: str) -> str:
    """Write (idempotently) and return the capture launcher shim.

    The filename is content-addressed (hash of the rendered script), so a
    changed feature list or Chrome path yields a new shim, re-running with the
    same inputs is a no-op, and concurrent tool invocations race safely via the
    atomic ``os.replace``.
    """
    script = _SHIM_TEMPLATE.format(
        real=shlex.quote(real_chrome),
        features=shlex.quote(features),
    )
    digest = hashlib.sha256(script.encode()).hexdigest()[:12]
    shim_dir = os.environ.get('DRP_CHROME_SHIM_DIR') or tempfile.gettempdir()
    shim_path = os.path.join(shim_dir, f'xasm-chrome-shim-{digest}.sh')
    if not os.path.exists(shim_path):
        tmp_path = f'{shim_path}.tmp-{os.getpid()}'
        with open(tmp_path, 'w', encoding='utf-8') as fh:
            fh.write(script)
        os.chmod(tmp_path, 0o755)
        os.replace(tmp_path, shim_path)
    return shim_path


def find_chrome_path() -> Optional[str]:
    """Chrome path handed to gowitness (``--chrome-path``).

    #1572 — returns a generated launcher shim wrapping the real Chrome so every
    capture runs with the HTTPS-upgrade features disabled (see
    ``DEFAULT_CHROME_DISABLE_FEATURES``). Fail-open on shim-write failure: the
    real binary is returned unwrapped, so capture keeps working minus the
    http-fallback fix. Returns None only when no Chrome exists at all (gowitness
    then downloads its own — the historical fallback, unchanged).
    """
    real = _find_real_chrome()
    if not real:
        return None
    features = _disable_features()
    if not features:
        return real  # operator kill-switch: no shim, use the real binary
    try:
        return _chrome_shim_path(real, features)
    except OSError:
        return real


def compute_sha256(file_path: str) -> str:
    """Compute SHA-256 hash of a file."""
    sha256 = hashlib.sha256()
    with open(file_path, 'rb') as f:
        for chunk in iter(lambda: f.read(8192), b''):
            sha256.update(chunk)
    return sha256.hexdigest()
